title: Hydn
email: example@example.com
description: >-
  Write an awesome description for your new site here. 
  You can edit this line in _config.yml. 
  It will appear in your document head meta (for Google search results) 
  and in your feed.xml site description.
baseurl: ""
url:
# avatar: *.jpg

#twitter_username:
#github_username:
#facebook_username:
#instagram_username:

logo:
lang: ko_KR

# Disqus
disqus: True
disqus_shortname: "hydn"
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해 disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )

tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tagpost.html]
    categories: []
    tags: []

navigation: True
# Navigation bar link를 보여줄건지 여부

subscribers: True
# subscriber 기능을 사용할건지의 여부

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Anonymous"
  - scope:
      path: ""
      type: "category-pages"
    values:
      layout: "category-page"
      permalink: /category/:title
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author-page"
      permalink: /author/:title
      image: assets/img/default-profile.png
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series-page"
      permalink: /series/:title

plugins:
  - jekyll-seo-tag

sass:
  style: compressed

collections:
  authors:
    output: true
  category-pages:
    output: true
    permalink: /:collection/:name
  series:
    output: true

paginate: 2
paginate_path: "/all/:num/"

date_format: "%Y/%m/%d"
